# Generated by Django 2.2.1 on 2019-06-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(blank=True, default='static/images/team/1.jpg', null=True, upload_to='fotos_usuarios/'),
        ),
    ]
