# Generated by Django 2.2.1 on 2019-06-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_auto_20190626_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(blank=True, default='static/images/team/1.jpg', null=True, upload_to='fotos_usuarios/'),
        ),
    ]
