# Generated by Django 2.2.1 on 2019-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_auto_20190626_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre,'), ('M', 'Mujer')], default=None, max_length=20, null=True),
        ),
    ]
