# Generated by Django 2.2.1 on 2019-06-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_auto_20190626_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(blank=True, default='static/fotos_users/user_I.png', null=True, upload_to='fotos_usuarios/'),
        ),
    ]
